name: traffic_sim
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.7.7=h886c30d_1
  - aws-c-cal=0.6.9=hea61927_1
  - aws-c-common=0.9.8=h93a5062_0
  - aws-c-compression=0.2.17=hea61927_6
  - aws-c-event-stream=0.3.2=h0574dc0_7
  - aws-c-http=0.7.14=h90b1786_2
  - aws-c-io=0.13.36=he1b4ce3_0
  - aws-c-mqtt=0.9.10=h8d54690_1
  - aws-c-s3=0.4.1=ha5b923c_0
  - aws-c-sdkutils=0.1.12=hea61927_5
  - aws-checksums=0.1.17=hea61927_5
  - aws-crt-cpp=0.24.7=hba4ac3b_6
  - aws-sdk-cpp=1.11.182=h31542fa_7
  - blosc=1.21.5=hc338f07_0
  - boost-cpp=1.78.0=hf1d6563_2
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py310h1af2607_4
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=had492bb_1012
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - cfitsio=4.2.0=h2f961c4_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h7f4e7e6_0
  - curl=8.16.0=h6430ca7_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - expat=2.7.3=h982b769_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - freexl=1.0.6=h1a8c8d9_1
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.11.2=hb7217d7_0
  - geotiff=1.7.1=hea8fa61_8
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.6.0=h6da1cb0_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h8111dcc_6
  - hdf5=1.14.0=nompi_h6b85c65_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h6b3803e_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.16=hc449e50_0
  - kealib=1.5.1=hc851fbe_3
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.20.1=h69eda48_0
  - lcms2=2.15=hd835a16_1
  - lerc=4.0.0=hd64df32_1
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.4=h51d1e36_0
  - libarrow=14.0.1=h63c4d5d_4_cpu
  - libarrow-acero=14.0.1=had9dd58_4_cpu
  - libarrow-dataset=14.0.1=had9dd58_4_cpu
  - libarrow-flight=14.0.1=h1011bfc_4_cpu
  - libarrow-flight-sql=14.0.1=h660fe36_4_cpu
  - libarrow-gandiva=14.0.1=h2b96968_4_cpu
  - libarrow-substrait=14.0.1=h594d712_4_cpu
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.18=h1a8c8d9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgdal=3.6.3=h90339d4_6
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.78.1=hd9b11f9_0
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=hbcf6334_0
  - libiconv=1.18=h23cfdf5_2
  - libidn2=2.3.8=ha90df94_1
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=2.1.5.1=hb547adb_1
  - libkml=1.3.0=hc4d7c42_7
  - liblapack=3.9.0=38_hd9741b5_openblas
  - libllvm15=15.0.7=h62b9111_1
  - libnetcdf=4.9.2=nompi_h9b03b3c_103
  - libnghttp2=1.58.0=ha4dd798_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libparquet=14.0.1=heaab74a_4_cpu
  - libpng=1.6.50=h280e0eb_1
  - libpq=15.2=h1a28acd_0
  - libprotobuf=4.24.4=h810fc01_0
  - libre2-11=2023.09.01=h741fcf5_1
  - librttopo=1.1.0=h6ecf6d2_13
  - libspatialite=5.0.1=hee00587_25
  - libsqlite=3.51.0=h9a5124b_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.5.1=h23a1a89_1
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.10.3=h67585b2_4
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_1
  - lz4-c=1.9.4=hb7217d7_0
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib=3.10.8=py310hb6292c7_0
  - matplotlib-base=3.10.8=py310h0181960_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=pyh267e887_2
  - nspr=4.38=heaf21c2_0
  - nss=3.117=h1c710a3_0
  - numpy=1.26.4=py310hd45542a_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.8=h81ee809_0
  - orc=1.9.2=h7c018df_0
  - osmnx=2.0.6=ha770c72_0
  - osmnx-base=2.0.6=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.40=hb34f9b4_0
  - pillow=10.0.0=py310h60ecbdf_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h81086ad_1
  - poppler=23.03.0=h15f6d88_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h45c140d_0
  - proj=9.2.0=h13f728c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.10.0=py310hcf39714_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.6.0=py310he41a1dd_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=h2469fbe_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rasterio=1.4.3=py310h9ce171c_0
  - re2=2023.09.01=h4cba328_1
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rio-vrt=0.3.1=pyhd8ed1ab_1
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310hca03da5_0
  - shapely=2.0.1=py310h605c0e7_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hd04f947_1
  - sqlite=3.51.0=hab6afd1_0
  - statsmodels=0.14.5=py310hfdc7867_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiledb=2.13.2=h9bd36d0_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py310hfe3a0ae_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzcode=2025b=h5505292_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py310hca03da5_0
  - xerces-c=3.2.4=h627aa08_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py310hf151d32_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aequilibrae==1.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blosc2==3.11.0
      - comm==0.2.3
      - cykhash==2.0.1
      - cython==3.2.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - duckdb==1.4.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - geoarrow-c==0.3.1
      - geoarrow-pandas==0.1.1
      - geoarrow-pyarrow==0.2.0
      - geoarrow-types==0.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - igraph==1.0.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keplergl==0.3.7
      - lark==1.3.1
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.10.0
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numexpr==2.14.1
      - openmatrix==0.3.5.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyaml==25.7.0
      - pyarrow==22.0.0
      - pyrobuf==0.9.3
      - pyrosm==0.6.2
      - python-json-logger==4.0.0
      - python-rapidjson==1.22
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - sodapy==2.2.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - tables==3.10.1
      - terminado==0.18.1
      - texttable==1.7.0
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.1
      - torch-geometric==2.7.0
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - traitlets==5.14.3
      - traittypes==0.2.3
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/traffic_sim
